### ISSUE TITLE
How to actually run the package?

### ISSUE THREAD

**Issue by rmdwirizki** [toji/semilive#2]
I have copied the files to the sublime Packages/User folder. But i still can't run `semilive_next` in the console saying `semilive_next` is not defined. I'm confused.

**Comment by rizerzero** [comment]
just add these lines to your keybindings 

`
        { "keys": ["ctrl+f6"], "command": "semilive_next" },
        { "keys": ["ctrl+f5"], "command": "semilive_reset" },`

**Comment by rmdwirizki** [comment]
oh it actually work just like that ._.
my thanks to you
